name: Continuous integration
on:
  push:
    branches: [master]
  workflow_call:
permissions:
  contents: read
jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/AliaumeL/ensps-colorscheme:main
    steps:
      - uses: actions/checkout@v4
      - run: |
          cd latex && make ensps.zip
      - uses: actions/upload-artifact@v4
        with:
          name: ensps-latex.zip
          path: latex/ensps.zip





